In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/customers.csv")

## CHECK DUPLICATES

In [3]:
customers.duplicated().sum()

np.int64(0)

In [4]:
plans = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/plans.csv")

In [5]:
plans.duplicated().sum()

np.int64(0)

In [6]:
customer_usage = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/customer_usage.csv")

In [7]:
customer_usage.duplicated().sum()

np.int64(0)

In [8]:
support_tickets = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/support_tickets.csv")

In [9]:
support_tickets.duplicated().sum()

np.int64(0)

In [10]:
transactions = pd.read_csv("C:/Users/hp/Desktop/customer-churn-analysis-python-/data/raw_data/transactions.csv")

In [11]:
transactions.duplicated().sum()

np.int64(0)

## CHECK DUPLICATES ID'S

In [12]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [13]:
plans["plan_id"].duplicated().sum()

np.int64(0)

In [14]:
transactions["transaction_id"].duplicated().sum()

np.int64(0)

In [15]:
support_tickets["ticket_id"].duplicated().sum()

np.int64(0)

In [16]:
customer_usage["usage_id"].duplicated().sum()

np.int64(0)

## MISSING VALUES

In [17]:
customers.isnull().sum()

customer_id            0
customer_name          0
gender                 0
age                    0
city                 300
state                  0
join_date              0
plan_id                0
contract_type          0
internet_service    1691
tenure_months          0
churn                  0
dtype: int64

In [18]:
customers["internet_service"].value_counts(dropna=False)

internet_service
Fiber    5837
DSL      4440
5G       3032
NaN      1691
Name: count, dtype: int64

In [19]:
customers.groupby(customers["internet_service"].isna())["churn"].value_counts(normalize=True)*100

internet_service  churn
False             No       76.527162
                  Yes      23.472838
True              No       75.753992
                  Yes      24.246008
Name: proportion, dtype: float64

In [20]:
customers["internet_service"]=customers["internet_service"].fillna("Unknown")

In [21]:
customers["internet_service"].value_counts()

internet_service
Fiber      5837
DSL        4440
5G         3032
Unknown    1691
Name: count, dtype: int64

In [22]:
customers["internet_service"].isnull().sum()

np.int64(0)

In [23]:
customers["city"].mode()

0    Ghaziabad
Name: city, dtype: object

In [24]:
customers["city"]=customers["city"].fillna(customers["city"].mode()[0])

In [25]:
customers["city"].isnull().sum()

np.int64(0)

In [26]:
customers["city"].value_counts().head()

city
Ghaziabad     394
Aurangabad     84
Junagadh       69
Durgapur       65
Guntur         64
Name: count, dtype: int64

In [27]:
plans.isnull().sum()

plan_id        0
plan_name      0
monthly_fee    0
dtype: int64

In [28]:
transactions.isnull().sum()

transaction_id    0
customer_id       0
payment_date      0
amount            0
payment_method    0
payment_status    0
dtype: int64

In [29]:
support_tickets.isnull().sum()

ticket_id             0
customer_id           0
issue_type            0
priority              0
resolution_days       0
satisfaction_score    0
dtype: int64

In [30]:
customer_usage.isnull().sum()

usage_id         0
customer_id      0
month            0
data_usage_gb    0
call_minutes     0
sms_count        0
dtype: int64

## CALCULATE MISSING PERCENTAGE

In [31]:
round(customers.isnull().mean()*100,2)

customer_id         0.0
customer_name       0.0
gender              0.0
age                 0.0
city                0.0
state               0.0
join_date           0.0
plan_id             0.0
contract_type       0.0
internet_service    0.0
tenure_months       0.0
churn               0.0
dtype: float64

## CHECK DATA TYPES

In [32]:
customers.dtypes

customer_id          int64
customer_name       object
gender              object
age                  int64
city                object
state               object
join_date           object
plan_id              int64
contract_type       object
internet_service    object
tenure_months        int64
churn               object
dtype: object

In [33]:
customers["join_date"].dtypes

dtype('O')

In [34]:
transactions.dtypes

transaction_id     int64
customer_id        int64
payment_date      object
amount             int64
payment_method    object
payment_status    object
dtype: object

In [35]:
transactions["payment_date"].dtypes

dtype('O')

In [36]:
customer_usage.dtypes

usage_id           int64
customer_id        int64
month             object
data_usage_gb    float64
call_minutes       int64
sms_count          int64
dtype: object

In [37]:
customer_usage["month"].dtypes

dtype('O')

## CONVERT DATE COLUMNS

In [38]:
customers["join_date"] = pd.to_datetime(customers["join_date"])

In [39]:
transactions["payment_date"] = pd.to_datetime(transactions["payment_date"])

In [40]:
customer_usage["month"] = pd.to_datetime(customer_usage["month"])

In [41]:
customers.dtypes

customer_id                  int64
customer_name               object
gender                      object
age                          int64
city                        object
state                       object
join_date           datetime64[ns]
plan_id                      int64
contract_type               object
internet_service            object
tenure_months                int64
churn                       object
dtype: object

In [42]:
transactions.dtypes

transaction_id             int64
customer_id                int64
payment_date      datetime64[ns]
amount                     int64
payment_method            object
payment_status            object
dtype: object

In [43]:
customer_usage.dtypes

usage_id                  int64
customer_id               int64
month            datetime64[ns]
data_usage_gb           float64
call_minutes              int64
sms_count                 int64
dtype: object

## CHECK CATEGORICAL VALUES

In [44]:
customers["gender"].value_counts(dropna=False)

gender
Male      7521
Female    7479
Name: count, dtype: int64

In [45]:
customers["state"].value_counts(dropna=False)

state
Gujarat           2279
Tamil Nadu        2180
Rajasthan         2175
Karnataka         2119
Delhi             2088
Madhya Pradesh    2081
Maharashtra       2078
Name: count, dtype: int64

In [46]:
customers["contract_type"].value_counts(dropna=False)

contract_type
Monthly     7508
Annual      4517
Two-Year    2975
Name: count, dtype: int64

In [47]:
customers["internet_service"].value_counts(dropna=False)

internet_service
Fiber      5837
DSL        4440
5G         3032
Unknown    1691
Name: count, dtype: int64

In [48]:
customers["churn"].value_counts(dropna=False)

churn
No     11466
Yes     3534
Name: count, dtype: int64

In [49]:
transactions["payment_method"].value_counts(dropna=False)

payment_method
UPI            20104
Net Banking    20045
Wallet         19946
Card           19905
Name: count, dtype: int64

In [50]:
transactions["payment_status"].value_counts(dropna=False)

payment_status
Paid      65691
Late       9501
Failed     4808
Name: count, dtype: int64

In [51]:
support_tickets["issue_type"].value_counts(dropna=False)

issue_type
Billing      3404
Refund       3356
Technical    3352
Speed        3336
Login        3305
Network      3247
Name: count, dtype: int64

In [52]:
support_tickets["priority"].value_counts(dropna=False)

priority
Medium    6764
High      6648
Low       6588
Name: count, dtype: int64

## CHECK NUMERICAL OUTLIERS

In [53]:
customers[["age","tenure_months"]].describe()

                age  tenure_months
count  15000.000000   15000.000000
mean      43.434133      30.431867
std       15.057542      17.206720
min       18.000000       1.000000
25%       31.000000      16.000000
50%       43.000000      30.000000
75%       57.000000      45.000000
max       69.000000      60.000000

In [54]:
customer_usage[[
    "data_usage_gb",
    "call_minutes",
    "sms_count"
]].describe()

       data_usage_gb  call_minutes     sms_count
count   45000.000000  45000.000000  45000.000000
mean      251.475980   2009.022644    249.115378
std       143.903597   1148.569007    144.354629
min         1.010000     20.000000      0.000000
25%       126.362500   1018.000000    125.000000
50%       252.920000   2007.000000    249.000000
75%       375.360000   3009.000000    374.000000
max       499.990000   3999.000000    499.000000

In [55]:
support_tickets[["resolution_days","satisfaction_score"]].describe()

       resolution_days  satisfaction_score
count     20000.000000        20000.000000
mean         10.452100            2.994750
std           5.752631            1.407736
min           1.000000            1.000000
25%           5.000000            2.000000
50%          10.000000            3.000000
75%          15.000000            4.000000
max          20.000000            5.000000

## Data Cleaning Summary

### Customers
- Checked duplicate records.
- Checked duplicate customer IDs.
- Analyzed missing values.
- Converted join_date to datetime.
- Checked categorical values.
- Reviewed numerical columns for potential outliers.

### Plans
- Checked duplicate records and plan IDs.
- Verified plan names and monthly fees.

### Transactions
- Checked duplicate transaction IDs.
- Converted payment_date to datetime.
- Checked payment methods and payment statuses.
- Reviewed transaction amounts.

### Customer Usage
- Checked duplicate usage IDs.
- Converted month to datetime.
- Reviewed data usage, call minutes, and SMS counts.

### Support Tickets
- Checked duplicate ticket IDs.
- Reviewed issue types and priorities.
- Checked resolution time and satisfaction scores.

### Next Step
The cleaned tables will be prepared for integration in the next stage.

In [56]:
customers["join_date"].describe()

count                         15000
mean     2023-03-08 18:38:41.280000
min             2021-01-01 00:00:00
25%             2022-01-29 00:00:00
50%             2023-03-12 00:00:00
75%             2024-04-15 00:00:00
max             2025-05-19 00:00:00
Name: join_date, dtype: object

## CHECK INVALID DATES

In [57]:
transactions["payment_date"].describe()

count                            80000
mean     2024-03-23 22:57:43.200000256
min                2023-01-01 00:00:00
25%                2023-08-10 00:00:00
50%                2024-03-23 00:00:00
75%                2024-11-06 00:00:00
max                2025-06-18 00:00:00
Name: payment_date, dtype: object

In [58]:
customer_usage["month"].describe()

count                            45000
mean     2024-07-01 12:15:42.720000256
min                2024-01-01 00:00:00
25%                2024-03-31 00:00:00
50%                2024-07-02 00:00:00
75%                2024-10-02 00:00:00
max                2024-12-30 00:00:00
Name: month, dtype: object

## CHECK NUMERIC COLUMNS

In [59]:
customers[["age","tenure_months"]].describe()

                age  tenure_months
count  15000.000000   15000.000000
mean      43.434133      30.431867
std       15.057542      17.206720
min       18.000000       1.000000
25%       31.000000      16.000000
50%       43.000000      30.000000
75%       57.000000      45.000000
max       69.000000      60.000000

In [60]:
transactions["amount"].describe()

count    80000.000000
mean      1401.161738
std        635.295792
min        299.000000
25%        851.000000
50%       1402.000000
75%       1955.000000
max       2499.000000
Name: amount, dtype: float64

In [61]:
customer_usage[["data_usage_gb","call_minutes","sms_count"]].describe()

       data_usage_gb  call_minutes     sms_count
count   45000.000000  45000.000000  45000.000000
mean      251.475980   2009.022644    249.115378
std       143.903597   1148.569007    144.354629
min         1.010000     20.000000      0.000000
25%       126.362500   1018.000000    125.000000
50%       252.920000   2007.000000    249.000000
75%       375.360000   3009.000000    374.000000
max       499.990000   3999.000000    499.000000

In [62]:
support_tickets[["resolution_days","satisfaction_score"]].describe()

       resolution_days  satisfaction_score
count     20000.000000        20000.000000
mean         10.452100            2.994750
std           5.752631            1.407736
min           1.000000            1.000000
25%           5.000000            2.000000
50%          10.000000            3.000000
75%          15.000000            4.000000
max          20.000000            5.000000

In [63]:
customer_usage["month"] = pd.to_datetime(customer_usage["month"])

In [64]:
customer_usage["month"].describe()

count                            45000
mean     2024-07-01 12:15:42.720000256
min                2024-01-01 00:00:00
25%                2024-03-31 00:00:00
50%                2024-07-02 00:00:00
75%                2024-10-02 00:00:00
max                2024-12-30 00:00:00
Name: month, dtype: object

In [65]:
customers["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [66]:
customers["contract_type"].unique()

array(['Two-Year', 'Monthly', 'Annual'], dtype=object)

## Outlier Analysis using IQR

In [67]:
def check_outlier(df, column):
    q1=df[column].quantile(0.25)
    q3=df[column].quantile(0.75)
    IQR = q3-q1
    lower_bound = q1-1.5*IQR
    upper_bound = q3+1.5*IQR
    outliers = df[(df[column]<lower_bound)|(df[column]>upper_bound)]
    print(f"column:{column}")
    print(f"lower bound : {lower_bound}")
    print(f"upper bound : {upper_bound}")
    print(f"Number of outliers : {len(outliers)}")
    return outliers

In [68]:
check_outlier(customers, "age")

column:age
lower bound : -8.0
upper bound : 96.0
Number of outliers : 0

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, city, state, join_date, plan_id, contract_type, internet_service, tenure_months, churn]
Index: []

In [69]:
check_outlier(customers, "tenure_months")

column:tenure_months
lower bound : -27.5
upper bound : 88.5
Number of outliers : 0

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, city, state, join_date, plan_id, contract_type, internet_service, tenure_months, churn]
Index: []

In [70]:
check_outlier(transactions, "amount")

column:amount
lower bound : -805.0
upper bound : 3611.0
Number of outliers : 0

Empty DataFrame
Columns: [transaction_id, customer_id, payment_date, amount, payment_method, payment_status]
Index: []

In [71]:
check_outlier(customer_usage, "data_usage_gb")

column:data_usage_gb
lower bound : -247.13375000000002
upper bound : 748.85625
Number of outliers : 0

Empty DataFrame
Columns: [usage_id, customer_id, month, data_usage_gb, call_minutes, sms_count]
Index: []

In [72]:
check_outlier(customer_usage, "call_minutes")

column:call_minutes
lower bound : -1968.5
upper bound : 5995.5
Number of outliers : 0

Empty DataFrame
Columns: [usage_id, customer_id, month, data_usage_gb, call_minutes, sms_count]
Index: []

In [73]:
check_outlier(customer_usage, "sms_count")

column:sms_count
lower bound : -248.5
upper bound : 747.5
Number of outliers : 0

Empty DataFrame
Columns: [usage_id, customer_id, month, data_usage_gb, call_minutes, sms_count]
Index: []

In [74]:
check_outlier(support_tickets,"resolution_days")

column:resolution_days
lower bound : -10.0
upper bound : 30.0
Number of outliers : 0

Empty DataFrame
Columns: [ticket_id, customer_id, issue_type, priority, resolution_days, satisfaction_score]
Index: []

In [75]:
check_outlier(support_tickets, "satisfaction_score")

column:satisfaction_score
lower bound : -1.0
upper bound : 7.0
Number of outliers : 0

Empty DataFrame
Columns: [ticket_id, customer_id, issue_type, priority, resolution_days, satisfaction_score]
Index: []

## DATA QUALITY CHECK

In [79]:
print("customers")
print("Missing Values:", customers.isnull().sum().sum())
print("Duplicate Rows :", customers.duplicated().sum())

customers
Missing Values: 0
Duplicate Rows : 0

In [80]:
print("n/Plans")
print("Missing Values:",plans.isnull().sum())
print("Missing Values:",plans.duplicated().sum())

n/Plans
Missing Values: plan_id        0
plan_name      0
monthly_fee    0
dtype: int64
Missing Values: 0

In [81]:
print("n/Transactions")
print("Missing Values:",transactions.isnull().sum())
print("Missing Values:",transactions.duplicated().sum())

n/Transactions
Missing Values: transaction_id    0
customer_id       0
payment_date      0
amount            0
payment_method    0
payment_status    0
dtype: int64
Missing Values: 0

In [85]:
print("n/Support Tickets")
print("Missing Values:",support_tickets.isnull().sum())
print("Missing Values:",support_tickets.duplicated().sum())

n/Support Tickets
Missing Values: ticket_id             0
customer_id           0
issue_type            0
priority              0
resolution_days       0
satisfaction_score    0
dtype: int64
Missing Values: 0

In [86]:
print("n/Customer Usage")
print("Missing Values:",customer_usage.isnull().sum())
print("Missing Values:",customer_usage.duplicated().sum())

n/Customer Usage
Missing Values: usage_id         0
customer_id      0
month            0
data_usage_gb    0
call_minutes     0
sms_count        0
dtype: int64
Missing Values: 0